# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuBar.setNativeMenuBar(False)
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLogOpen = QtWidgets.QAction(MainWindow)
        self.actionLogOpen.setObjectName("action")
        self.actionLogExport = QtWidgets.QAction(MainWindow)
        self.actionLogExport.setObjectName("action_2")
        self.actionLogAdd = QtWidgets.QAction(MainWindow)
        self.actionLogAdd.setObjectName("action_3")
        self.actionLogWatch = QtWidgets.QAction(MainWindow)
        self.actionLogWatch.setObjectName("action_4")
        self.menu.addAction(self.actionLogOpen)
        self.menu_2.addAction(self.actionLogExport)
        self.menu_2.addAction(self.actionLogAdd)
        self.menu_2.addAction(self.actionLogWatch)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Лог"))
        self.actionLogOpen.setText(_translate("MainWindow", "Открыть"))
        self.actionLogExport.setText(_translate("MainWindow", "Экспорт..."))
        self.actionLogAdd.setText(_translate("MainWindow", "Добавить в лог"))
        self.actionLogWatch.setText(_translate("MainWindow", "Просмотр"))
